apiVersion: apps/v1
kind: Deployment
metadata:
  name: cook-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cook-service
  template:
    metadata:
      labels:
        app: cook-service
    spec:
      containers:
        - name: cook-service
          image: your-dockerhub-username/cook-service:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cook-service
spec:
  selector:
    app: cook-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
