services:
  cook-service:
    build:
      context: ./services/cookServices/src
    container_name: cook-service
    ports:
      - "3001:3000"
    networks:
      - app-network

  order-service:
    build:
      context: ./services/orderServices/src
    container_name: order-service
    ports:
      - "3002:3000"
    depends_on:
      - cook-service
    networks:
      - app-network

  billing-service:
    build:
      context: ./services/billServices/src
    container_name: billing-service
    ports:
      - "3003:3000"
    depends_on:
      - order-service
    networks:
      - app-network

  frontend:
    build:
      context: ./services/frontEnd/src
    container_name: frontend
    ports:
      - "8081:80"
    depends_on:
      - cook-service
      - order-service
      - billing-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
