apiVersion: apps/v1
kind: Deployment
metadata:
  name: cooking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cooking-service
  template:
    metadata:
      labels:
        app: cooking-service
    spec:
      containers:
      - name: cooking-service
        image: tejachilumula007/cook_apis.1.0:cook_apis.1.0
        ports:
        - containerPort: 3002

---

apiVersion: v1
kind: Service
metadata:
  name: cooking-service
spec:
  selector:
    app: cooking-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: NodePort

